ac-nim.el

`eval-after-load` second argument must be a quoted form.

Quote eval-after-load form.

---

nim-mode.el

This fixes indentation of  `case` statement

Fix missing "of"

---

nim-mode.el

I seem you are missing those functions. Sorry if you have reasons about this.
About `nim-syntax-count-quotes`, I just borrowed from python.el.

Fix missing functions to suppress byte-compile warning

---

nim-mode.el

I'm new enough to nim that I don't know if it works in all cases. There's nothing I found in the language (nim or python) that would explain the original code which makes me hesitant to call this a real fix.
The specific case that was giving me trouble was with the for loop:
for x,y,z in bla():
^ would indent to here (last comma) instead of a single indent

Possible fix for indentation problem with for a,b,c in foo():

---

nim-thing-at-point.el

As requested in #3.
Possible defcustoms:
- `nim-get-thing-at-point-formatter` formatter function that is responsible for formatting nimsuggest result. For now can be `nim-thing-at-point-buffer` or `nim-thing-at-point-plain`. buffer version uses `nim-mode` to colorize output.
- `nim-get-thing-at-point-delay` delay for displaying `thing-at-point`.

thing-at-point feature for nim-mode

---

nim-indent.el
nim-mode.el
nim-rx.el
nim-syntax.el
nim-vars.el
tests/samples/import-statement-actual.nim
tests/samples/import-statement-expected.nim
tests/samples/line-end-indent-actual.nim
tests/samples/line-end-indent-expected.nim
tests/test-indent.el

Sorry, when I made #35, I had been avoided your indentation logic about "object", "tuple", "enum" and "object of". This PR fixes those indentation.
Also I found that "import" statement didn't work well, so I fixed it too.
Lastly I moved `nim-rx-* ` related variables to nim-rx.el because those variables needs `eval-and-compile` and it's easy to maintain if those are same file.
I wish you like this refactoring:)
Thanks

Fix indentation

---

.travis.yml
Cask
Makefile

Hi, working with travis is much easier to check building status.
I added basic settings and I checked that 24.3 and 24.4 were doing
tests. (But a test was failed. Other 8/9 were fine.)
Old version's Emacs 24.1 and 24.2 weren't working the test on Travis.
Probably need research???
But if you don't support old version's Emacs, you can exclude from
your test by just comment out below setting of .travis.yml.
```sh
...
- EVM_EMACS=emacs-24.1-bin
- EVM_EMACS=emacs-24.2-bin
...
```

Add Travis CI configuration file

---

Makefile

I would skip the cask install when I already have it because installing those packages need some
time. (I frequently type `make test` before I send PR)

Skip installation of dependencies if .cask is exists

---

nim-helper.el
nim-indent.el
tests/indents/for-pairs-actual.nim
tests/indents/for-pairs-expected.nim

Sorry, #53 had a bug when I indent following case:
```nim
if true:
for x in obj:
echo "this line doesn't indent..."
```

Fix indent

---

Makefile
nim-indent.el
tests/indents/indent-after-colon-actual.nim
tests/indents/indent-after-colon-expected.nim
tests/test-indent.el

This PR enables indentation after ":". 
Originally, I thought supporting template's indentation, but it indents
other nim-mode's missing indentation. (like defer)
Please correct me if there are another usage of ":"
(I'm still learning Nim)

Indent after colon

---

company-nim.el
nim-compile.el
nim-fill.el
nim-helper.el
nim-indent.el
nim-mode.el
nim-rx.el
nim-suggest.el
nim-syntax.el
nim-thing-at-point.el
nim-util.el
nim-vars.el
tests/test-indent.el
tests/test-syntax.el

- Use cl-lib functions/macros instead of cl.el
- Enable lexical-binding at all files. This package supports Emacs 24 or higher, so it is no problems.
- Remove lexical-let.

Remove cl.el dependency

---

nim-mode.el

to enable font-lock in .nims and .nimble files

Apply nims and nimble file extensions

---

nim-rx.el
nim-syntax.el
nim-vars.el
tests/syntax/export.nim
tests/syntax/function_name.nim
tests/test-syntax.el

Added features highlighting tabs, exports(like XXX*,  probably same as #51), and
some essential types (from system.nim)

Improve syntax highlight (including #51)

---

README.md
nim-eldoc.el
nim-smie.el
tests/indents/SMIE/comma.nim
tests/indents/SMIE/const.nim
tests/indents/SMIE/let.nim
tests/indents/SMIE/method.nim
tests/indents/SMIE/type.nim
tests/indents/SMIE/var.nim

Sorry, for frequency update. I noticed some wrong indent when I was using 
`object`s indentation.

Improve smie's indentation

---

nim-helper.el
nim-mode.el
nim-syntax.el
nim-vars.el
tests/syntax/multiline_comment.nim
tests/test-syntax.el

This PR enables highlighting multiline comment (#[]# and ##[]##)
The test is based on /tests/parser/tmultiline_comments.nim at devel branch.

Multiline comment

---

nim-fill.el
nim-mode.el
nim-smie.el
nim-util.el

I noticed `electric-indent-inhibit` isn't enough for specific emacs 24.4 from this 
discussion: https://github.com/haskell/haskell-mode/issues/377
So, I added `nim-indent-line` function to `electric-indent-functions-without-reindent`, 
which is block list for electric-indent. I hope this PR solve #54 as well.

Add nim-indent-line function to Elctric indent's block list #54

---

Cask
README.md
nim-mode.el
nim-smie.el
nim-syntax.el
nim-vars.el

In multi-line comment, comment-region and uncomment-region functions didn't work
correctly.

Apply multi line comment/uncomment region functions

---

README.md
nim-mode.el
nim-rx.el
nim-syntax.el
nim-vars.el
tests/syntax/backtick.nim
tests/syntax/format.nim
tests/syntax/test_is_and_distinct.nim
tests/test-syntax.el

Added some new highlights and refinements:
1. highlight word after `is`
2. highlight word after `distinct`
3. use different logic for pragma highlight.
4. highlight $# and $[1-9] for format in string
5. highlight backticks in comment
(Please merge #81 first)

Improve highlighting

---

nim-smie.el
tests/indents/SMIE/case-stmt.nim
tests/indents/SMIE/if-stmt.nim
tests/indents/SMIE/type.nim
tests/indents/SMIE/when-stmt.nim

Fix wrong indent if the sentence is including `in`.
(note that we already have `for x in ..` test)
EDIT:
I noticed this wrong indent when I visited Nim/compiler/nimfix/pretty.nim
and copied from it to make the test.

Fix smie's indent

---

company-nim.el
nim-suggest.el
nim-vars.el

- added `--define:nimscript` and `--define:nimconfig` options for nimscript files
(it allows you to more precise completion)
- added a function to get data from system.nim for auto-completion
and it includes nimscript's data as well because of the change I wrote above.
(sorry for frequency change. I didn't know I could specify --define:nimscirpt)

Auto completion for system.nim

---

nim-smie.el
tests/indents/SMIE/paren-space.nim

I (and some others) like to put a space inside my parentheses when they surround arguments, like `f( x, y )` rather than `f(x,y)`. This patch makes nim-mode indent comma-separated expressions on multiple lines correctly when the parentheses surrounding them have extra space. The added test demonstrates the effect.

Deal with spaces after open parens

---

company-nim.el

Sometimes auto completion leaves a space or newline when I activate 
auto-completion first time in the buffer.
This PR fixes the wrong behavior.

Fix inaccurate calculation

---

nim-syntax.el
nim-vars.el

added a feature to convert triple double quotes to another form for pretty-symbols-mode.
(the first line's “foo”)

Pretty symbols

---

nim-suggest.el

Should we use more accurate name as nimsuggest's dirty directory?
http://forum.nim-lang.org/t/2136

Modify temp directory name (added emacs-nim-mode directory as prefix)

---

nim-suggest.el

I think `nim-epc-processes-alist` has to be deleted with epc.el's function, 
So I added it. and I also added a feature to remove temporary directory for nimsuggest
after users quit emacs.
hope this PR helps http://forum.nim-lang.org/t/2136
(but, I'm not entirely sure though)

Kill zombie processes

---

Cask
flycheck-nim-async.el
nim-suggest.el

when I moved a nim file to another nim file, somehow my cursor went to bottom of buffer.
(`save-excursion` function should prevent, but it doesn't...)
This PR fixes above problem.

Fix moving around cursor in flycheck async nim

---

nim-mode.el

for flycheck-nim-async and company-mode
(just remainder for me, MELPA refers pkg dependencies of nim-mode.el, not each files
because `nim-mode` is repository name)

Fix package dependencies #100

---

contributing.md
nim-eldoc.el
nim-mode.el
nim-suggest.el

At #108, I realized current nim-mode wasn't easy to distinguish problems.
(whether it's nimsuggest related or font-lock related, for example)
This PR allows users easy setting to turn off some feature for nim-mode
1. turn off nimsuggest: `(defconst nim-nimsuggest-path nil)`
2. ~~turn off syntax-highlight~~: `(defconst nim-font-lock-keyword-list nil)`
(this feature didn't pass test, so I removed from this PR)

Refactor for debugging

---

.travis.yml
nim-mode.el
ob-nim.el
tests/test-ob-nim.el

I adapted ob-C.el for the nim language to enable nim-mode in  org's `begin_src` block.
As `nim-mode` already deals with everything nim, i would like to add it here and not a separate packages.

Add support for nim to org-mode's babel languages

---

flycheck-nim-async.el
nim-mode.el

In latest flycheck, flycheck-checker-modes function doesn't exist, so
I used flycheck-checker-get function instead.

Fix flycheck warning

---

nim-eldoc.el
nim-mode.el
nim-syntax.el
nim-vars.el
nimscript-mode.el

`font-lock-maximum-decoration` variable is normal way to change font lock highlight in Emacs. (and I didn't know that until recently)

Change font-lock-highlight by font-lock-maximum-decoration

---

nim-compile.el

to prevent needless output like Processing [XXX]

Modify default compile command

---

nim-eldoc.el
nim-mode.el
nim-suggest.el
nim-vars.el

Fixed
1. unhighlight single comment on org src block
2. turn off nim-eldoc on org src block (otherwise it emits annoying output)

Fix comment highlight and eldoc support on org mode

---

nim-eldoc.el
tests/test-ob-nim.el

global-eldoc-mode will be introduced in emacs 25, but it doesn't exist in emacs 24.4, and 24.5.
I omitted an ob-nim's test because of #132.

Fix warning for emacs24.4 and emacs24.5

---

Cask
README.md
company-nim.el
flycheck-nimsuggest.el
nim-capf.el
nim-eldoc.el
nim-helper.el
nim-mode.el
nim-suggest.el
nim-syntax.el
nim-vars.el

Removed company-nim.el and added nim-capf.el instead.
The capf is short of `completion-at-point-functions`, which is Emacs' default
completion feature (`M-/` key) and company-mode also supports this future as `company-capf`.
Also, I added `nimsuggest-mode` minor-mode, which activate nimsuggest related futures (el-doc, capf, flycheck) because sometimes nimsuggest is unstable when you use with nim's devel branch and switching `nimsuggset-mode` might help to distinguish the problem.

Add nim-capf and nimsuggest-mode

---

flycheck-nimsuggest.el
nim-suggest.el

For commit in nim repository: 6c0304f nimsuggest chk works for EPC

Apply nimsuggest's new error format for chk method #154

---

nim-compile.el
nim-mode.el

I have this change now already for quite a while in my other pull request that had some controversy because of my changes on how compilation works. This pull request has only the part for parsing the compilation error messages.
I added --excessiveStackTrace:on so that stack traces have absolute paths. This makes clicking on them work more often, when the files are not in the current project.

allow emacs to parse nim error messages from the compilation buffer

---

.github/CONTRIBUTING.md
README.md
flycheck-nimsuggest.el
nim-capf.el
nim-eldoc.el
nim-mode.el
nim-rx.el
nim-suggest.el
nim-syntax.el
nim-vars.el

- added xref's find definitions and references commands (xref introduced from Emacs 25.1)
- some variables and functions were renamed with nimsuggest prefix
- obsolete nim-tab-face because whitespace-mode does much better job and user configurable

Support xref library and some refactor

---

nim-capf.el

Keep global `completion-at-point-functions` hook clean, as it is generic hook used by many modes.
Other modes like `lisp-interaction-mode` and `python-mode` seem to keep this convention as well.
Just noticed that this is part of major mode conventions:
https://www.gnu.org/software/emacs/manual/html_node/elisp/Major-Mode-Conventions.html#Major-Mode-Conventions

Make completion-at-point-functions as local hook

---

nim-rx.el
nim-smie.el
nim-vars.el

Since the `func` keyword is finally usable on the current devel as a {.noSideEffects.} proc, I thought it'd be a good idea to include it into nim-mode. Otherwise using it is... ugly.
Only just looked into the code for the first time, so I hope I didn't forget to add something somewhere. Seems to work fine for me.

add "func" as a keyword for a {.noSideEffects.} proc

---

nim-suggest.el

The code incorrectly assumed that the frame number is going always to be at the third place in the split string, but the emacs frame title which is included in the string extracted with `(selected-frame)` can actually be customized using the `frame-title-format` var and might include spaces.
On Windows this actually made the extension completely unusable for me, since it erroneously extracted the full file path from my customized frame title which made it impossible to create the necessary temp file (on Windows filenames can't include colons like in `C:\foo.nim`).

Fix extracting the frame number

---

nim-suggest.el

Newlines in the doc output are simply getting stripped, which results in docs shown in eldoc looking like this:
`Marks ``socket`` as accepting connections.``Backlog`` specifies the maximum length of thequeue of pending connections.Raises an OSError error upon failure.`
With this change it looks like this:
`Marks ``socket`` as accepting connections. ``Backlog`` specifies the maximum length of the queue of pending connections.  Raises an OSError error upon failure.`

Preserve doc spaces in eldoc

---

nim-syntax.el
nim-vars.el

Initially I thought to highlight everything past a colon as a type. This worked great for my style of programming but in the Nim repository it is far too often normal code after a colon. The new heuristic is, everything starting with a capital letter is a type. Makes constants such as ``Pi`` highlighted as types as well.

font lock changes

---

nim-capf.el
nim-mode.el
nim-suggest.el

I convert autoload comments to commands.  When I load the library with ``load-library`` the autoload mock isn't generated. These commands are now executed twice, but in general it lowers the entrance barrier to contribute to nim-mode, because the ``autoload`` indirection isn't required anymore to load the library properly.
I do thins, because I think autoload here really gets in the way. Loading a library with ``load-library`` is properly documented. Loading the autoload mock of a library that needs to be generated first is not properly documented. Apart from that ``autoload`` is very confusing in it's name, it does the exact opposite of automatically loading something. With this change cloning nim-mode and loading it with ``(add-to-list 'load-path "/path/to/nim-mode/") (load-library …

No autoload dependency

---

nim-mode.el

`nim--set-font-lock-keywords` was (incorrectly) called recursively, iff `font-lock-maximum-decoration` is an alist.
This patch changes the call to `nim--set-font-lock-keywords` to `nim--get-font-lock-keywords` which seems to be correct.
This fixes #228.

Support alist form of font-lock-maximum-decoration

---

README.md

In README.md there is a configuration code example:
```
;; Make files in the nimble folder read only by default.
;; This can prevent to edit them by accident.
(when (string-match "/\.nimble/" buffer-file-name) (read-only-mode 1))
```
However this line is problematic when buffer-file-name returns nil. 
In peculiar if you try to html-export (C-c C-e h o) this org-mode file: 
```
#+begin_src nim
echo "Hello"
#+end_src
#+RESULTS:
: Hello
```
you get this error:
```
Debugger entered--Lisp error: (wrong-type-argument stringp nil)
string-match("/.nimble/" nil)
(if (string-match "/.nimble/" buffer-file-name) (progn (read-only-mode 1)))
(when (string-match "/.nimble/" buffer-file-name) (read-only-mode 1))
```
This PR fixes this by replacing:
` (when (string-match "/\.nimble/" buffer-file-name) …

Fix nil buffer-file-name in doc config example

---

nim-mode.el

Fixes `"File mode specification error: (error ‘org-element-at-point’ cannot be used in non-Org buffer" (org 9.6)`

org-element-at-point cannot be used in non-Org buffer

---

nim-compile.el

Fixes  nim-lang/nim-mode#240.  
Since `nim-compile--get-compile-command` is calling `nim--fmt` which applies `shell-quote-argument` to the compile command, arguments and file name there is no need to quote `buffer-file-name`.

Prevent double call to shell-quote-argument.

---

nim-suggest.el

#246 wasn't entirely fixed, the error still occurs when using eldoc to display symbol information. The code in this function is the same as in the other PR, it's just missing the same guard here.

Fix 'org-element-at-point' eldoc error
