nim-lang/nim-mode

README.md
I was having issues with indentation in nim-mode, being unable to end a code block and return re-indenting everything. It turns out nim needs to be treated similarly to python with multiple indent levels. If you are using auto-indent-mode this can be changed pretty easily. I propose you add this to the README.md to make it easier for newcomers to figure that out.
=> Documentation addition

company-nim.el, nim-mode.el
One fix one commit. I can rebase if needed though.
=> Company backend fixes / improvements (one fix one commit)

tests/syntax/string.nim, tests/test-syntax.el
I added some tests for syntax highlighting.
You can see the test result here : https://travis-ci.org/yuutayamada/nim-mode/builds/69838479
=> Add some syntax tests

nim-helper.el, tests/indents/when-stmt-actual.nim, tests/indents/when-stmt-expected.nim, tests/test-indent.el
Hi, I implemented `elif` and `else` indentation of  `when` statement with a basic test.
=> Implement elif and else indentation of when statement

nim-helper.el, nim-mode.el, tests/syntax/docstring.nim, tests/test-syntax.el
This PR enables docsctring(##)'s font lock face.
=> Support doc face

nim-suggest.el
Removed hints, warnings, etc. from nimsuggest output
=> Fixed issue #60

.travis.yml
See https://github.com/rejeep/evm
=> Apply travis' sudo duprecation warning

nim-eldoc.el
This package (eldoc support) automatically turns on if users set `nim-suggest-path`.
=> Apply eldoc support

nim-eldoc.el
Sorry, I didn't notice this (somehow I was checking,
byte compiled version)
pcase doesn't allow the "_" (, but you can use it
if the element is only one)
=> Fix wrong pcase style

tests/indents/SMIE/case-stmt.nim, tests/indents/SMIE/if-stmt.nim, tests/indents/SMIE/when-stmt.nim
Added some tests discussed in #76.
Sorry, if those tests are failed. In my environment(emacs master branch)
those tests are worked fine, so I wanted to make sure other emacs too.
=> Add indentation tests for #76

nim-syntax.el, tests/syntax/varargs.nim, tests/test-syntax.el
This PR fixes highlighting face of varargs.
=> Fix varargs highlight

nim-syntax.el, tests/syntax/multiline_comment.nim, tests/test-syntax.el
Sorry, there were some highlighting bug for multi line comment.
=> Fix multicomment highlight

README.md, nim-eldoc.el, nim-helper.el, nim-suggest.el, nim-vars.el
applied some other information: var, let, const, macro, template.
One thing, I'm not sure is --v2 option. I could make sure company-mode and worked
normally, but if you have something worry about, please let me know
=> Eldoc: more information

nim-eldoc.el, nim-mode.el, nim-vars.el, tests/syntax/test_nimscript.nims, tests/test-syntax.el
I divided nim-mode and nimscript-mode. Also I added highlights for nimscript files.
My main reason is easy configuration for flycheck-nim. I think it needs specific configuration
if current file is nimscript file.
=> Add nimscript mode

Cask, flycheck-nim-async.el, nim-suggest.el, nim-vars.el
Apply asynchronous syntax check to this nimsuggest:
https://github.com/nim-lang/nimsuggest/pull/22
=> Add flycheck-nim-async

starterKit.nims
probably it's convenient for Emacs newbies. I think
=> Add starterKit.nims

nim-eldoc.el
I forgot to add global-eldoc-mode to turn off eldoc-mode.
=> Fix missing a guard condition

nim-syntax.el, nim-vars.el, nimscript-mode.el
=> Turn off syntax highlight in big files #108

nim-smie.el, nim-vars.el, tests/indents/SMIE/using.nim
for Nim version 0.14.0
(http://nim-lang.org/news/2016_06_07_version_0_14_0_released.html)
=> Add indentation of `using` statement

company-nim.el
I updated nim and nimsuggest recently and it seems those are improved. (return more completion result) but in comapny-nim, it shows completion result even just input spaces. This PR prevent showing auto-completion if cursor is on just a space.
=> Fix company nim

nim-syntax.el, tests/syntax/single_comment.nims, tests/test-syntax.el
I found a wrong highlight and this PR fix the wrong highlight for comment
=> Fix comment highlight

README.md, nim-suggest.el
1. update readme.md
2. added frame number to nimsuggest's dirty directory to prevent
reading the same file from different emacsclients.
=> Minor update

nim-compile.el, nim-vars.el, nimscript-mode.el
=> Fix nimscript highlight

nim-eldoc.el, nim-suggest.el
seems it issue a query continuously regardless of cursor point
=> Fix eldoc and nimsuggest issue

README.md, nim-compile.el, nim-mode.el, nim-suggest.el, nim-util.el, nim-vars.el
(nimsuggest's flymake has often stopped when you input incorrect sentence in the code. it lead flymake's
panic)
=> Update document and fix flymake issue

nim-mode.el
I wanted to pin a version for flycheck-nimsuggest (of package requirement)
=> Bump up version

.github/CONTRIBUTING.md, README.md, nim-capf.el, nim-eldoc.el, nim-mode.el, nim-suggest.el, nim-vars.el
- #183 
- turn on xref features with nimsuggest-mode
- reduce eldoc call of nimsuggest
=> Some fixes

nim-suggest.el
Hello.
First, thank you for this package. I have started using nim right now.
When I start emacs, example: emacs test.nim, flycheck don't finish checking test.nim file.
Then I restart flycheck (M-x flycheck-mode, M-x flycheck-mode) and checking finish properly.
(add-hook 'prog-mode-hook 'flycheck-mode)
(add-hook 'nim-mode-hook 'nimsuggest-mode)
;; elpa autoloaded
;; (add-hook 'nimsuggest-mode-hook 'flycheck-nimsuggest-setup)
Best regards. Hector
=> Fixed not-stated misstyping & flycheck never ready

README.md
overhaul of the README file. Generally I worked on everything in the readme. But the important changes are the following:
* I made aware of some of the problems that are to be expected when using nimsuggest or electric indentation.
* I added a guide to prevent the known problems with nim-mode.
* There is a small introduction of the individual components that work together in nim-mode.  I was certainly overwhelmed when I first saw all these mode names and I had no idea what they meant. I hope now it is a little less intimidating. 
I don't expect you to merge this in right away, but at least let me know what you think about it.
fixes https://github.com/nim-lang/nim-mode/issues/37
=> more in depth readme

nim-suggest.el
- It causes trouble if you don't have cl loaded
=> Use cl-incf instead of incf

nim-mode.el, nim-rx.el
=> fix(rx): Byte compile error

.github/workflows/test.yml, .gitignore, Eask, Makefile, nim-mode.el
Add basic tests using Eask. 
Current tests:
- Test packaging (into `tar`)
- Test install
- Test byte-compile
See the log in https://github.com/jcs-PR/nim-mode/actions/runs/6344019152?pr=1.
There is an error in the Emacs windows snapshot, and we should ignore that for now. I've added the `experimental` flag so the badge will remain green [![CI](https://github.com/jcs-PR/nim-mode/actions/workflows/test.yml/badge.svg)](https://github.com/jcs-PR/nim-mode/actions/workflows/test.yml).
=> test: Build with Eask
